### ISSUE TITLE
Error en el comando npm run lint

### ISSUE THREAD

**Issue by geekhadev** [CodelyTV/cra-template-codely#1]
Estuve revisando un poco la herramienta y me tiró de este error cuando intenté hacer un `npm run lint`

```
Oops! Something went wrong! :(
ESLint: 8.28.0
Error: package.json » eslint-config-codely/typescript#overrides[0]
```

Traté de corregirlo pero no soy tan experto, al menos espero que la contribución de la notificación valga.

**Comment by nuria-fl** [comment]
Hola! Lo hemos arreglado en [eslint-config-codely](https://github.com/CodelyTV/eslint-config-codely/issues/5). Fue provocado por un breaking change introducido en una versión minor de typescript/eslint: https://github.com/typescript-eslint/typescript-eslint/issues/6132

Si ya tienes un proyecto creado con este template puedes arreglarlo subiendo manualmente la versión de eslint-config-codely a la 2.1.2.

Gracias por el aviso!
